version: '3.4'

services:
  recipe-maker-api:
    image: mcr.microsoft.com/devcontainers/python:1-3.9-bullseye
    build:
      context: RecipeMakerApi
    volumes:
      - .:/workspace
    ports:
      - 8000:8000
    links:
      - redis

  redis:
    image: redis:7.0.8
    ports:
      - "6379:6379"
